[package]
name = "kitty_proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = {version = "1.0.76", features = ["std"]}
log = "0.4.14"
pretty_env_logger = "0.5.0"
serde = {version="1.0.193", features=["serde_derive"]}
snafu = "0.7.0"
thiserror = "1.0.30"
tokio = { version = "1.15.0", features = ["full"] }
